// Generated by CoffeeScript 1.3.3
(function() {
  var Chromosome, Population, Simulator, global;

  Chromosome = (function() {
    var CHARS, i;

    CHARS = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; _i <= 15; i = ++_i) {
        _results.push(i.toString(16));
      }
      return _results;
    })();

    function Chromosome(code, cost) {
      this.code = code != null ? code : '';
      this.cost = cost != null ? cost : 9999;
      this.mutationCount = 0;
    }

    Chromosome.prototype.getCode = function() {
      return this.code;
    };

    Chromosome.prototype.getCost = function() {
      return this.cost;
    };

    Chromosome.prototype.getMutationCount = function() {
      return this.mutationCount;
    };

    Chromosome.prototype.calculateCost = function(targetCode) {
      var cost, totalCost, _i, _ref;
      totalCost = 0;
      for (i = _i = 0, _ref = this.code.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        totalCost += (cost = this.code.charCodeAt(i) - targetCode.charCodeAt(i), cost * cost);
      }
      return this.cost = totalCost;
    };

    Chromosome.prototype.randomize = function(length) {
      var charIndex, code;
      code = '';
      while (length-- > 0) {
        charIndex = Math.floor(Math.random() * CHARS.length);
        code += CHARS[charIndex];
      }
      return this.code = code;
    };

    Chromosome.prototype.mate = function(chromosome) {
      var combination1, combination2, midIndex, targetCode;
      targetCode = chromosome.getCode();
      midIndex = Math.round(this.code.length / 2) - 1;
      combination1 = this.code.slice(0, midIndex + 1 || 9e9) + targetCode.slice(midIndex + 1);
      combination2 = targetCode.slice(0, midIndex + 1 || 9e9) + this.code.slice(midIndex + 1);
      return [new Chromosome(combination1), new Chromosome(combination2)];
    };

    Chromosome.prototype.mutate = function() {
      var charIndex, offset, offsetChar, offsetIndex, randomChar, randomIndex;
      randomIndex = Math.floor(Math.random() * this.code.length);
      offset = Math.random() <= 0.5 ? -1 : 1;
      randomChar = this.code.charAt(randomIndex);
      charIndex = CHARS.indexOf(randomChar);
      offsetIndex = Math.abs(charIndex + offset) % CHARS.length;
      offsetChar = CHARS[offsetIndex];
      this.code = this.code.slice(0, randomIndex) + offsetChar + this.code.slice(randomIndex + 1);
      return this.mutationCount++;
    };

    return Chromosome;

  })();

  Population = (function() {

    function Population(targetCode, size, factor) {
      var chromosome, i, _i, _ref;
      this.targetCode = targetCode;
      this.size = size;
      this.factor = factor;
      this.members = [];
      this.generationCount = 0;
      for (i = _i = 0, _ref = this.size; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        chromosome = new Chromosome();
        chromosome.randomize(this.targetCode.length);
        this.members.push(chromosome);
      }
    }

    Population.prototype.getGenerationCount = function() {
      return this.generationCount;
    };

    Population.prototype.getMembers = function() {
      return this.members;
    };

    Population.prototype.getBestMembers = function() {
      return this.members.slice(0, 3);
    };

    Population.prototype.sort = function() {
      return this.members.sort(function(member1, member2) {
        return member1.getCost() - member2.getCost();
      });
    };

    Population.prototype.getNextGeneration = function() {
      var member, subgeneration, subgeneration1, subgeneration2, _i, _j, _len, _len1, _ref, _ref1;
      _ref = this.members;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        member = _ref[_i];
        member.calculateCost(this.targetCode);
      }
      this.sort();
      subgeneration1 = this.members[0].mate(this.members[1]);
      subgeneration2 = this.members[2].mate(this.members[3]);
      subgeneration = subgeneration1.concat(subgeneration2);
      this.members.splice(this.members.length - subgeneration.length, subgeneration.length, subgeneration[0], subgeneration[1], subgeneration[2], subgeneration[3]);
      _ref1 = this.members;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        member = _ref1[_j];
        if (Math.random() > this.factor) {
          continue;
        }
        member.mutate();
        member.calculateCost(this.targetCode);
        if (member.getCode() === this.targetCode) {
          return true;
        }
      }
      this.generationCount++;
      return false;
    };

    return Population;

  })();

  Simulator = (function() {

    function Simulator(width, height) {
      this.layout = d3.layout.pack().sort(null).size([width, height]).padding(2);
      this.vis = d3.select("#chart").append("svg").attr("width", width).attr("height", height);
    }

    Simulator.prototype.run = function(targetCode, callback, populationSize, mutationFactor) {
      var population, tick, timeout,
        _this = this;
      if (populationSize == null) {
        populationSize = 20;
      }
      if (mutationFactor == null) {
        mutationFactor = 0.5;
      }
      population = new Population(targetCode, populationSize, mutationFactor);
      timeout = null;
      tick = function(result) {
        if (result) {
          return clearTimeout(timeout);
        }
        console.log("" + (population.getGenerationCount()));
        result = population.getNextGeneration();
        _this.displayPopulation(population);
        if (callback != null) {
          callback.call(_this, population);
        }
        timeout = setTimeout(function() {
          return tick(result);
        }, 150);
        return result;
      };
      return tick(false);
    };

    Simulator.prototype.displayPopulation = function(population) {
      var data, member, node;
      data = (function() {
        var _i, _len, _ref, _results;
        _ref = population.getMembers();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          member = _ref[_i];
          _results.push({
            color: member.getCode(),
            value: 4 + Math.sqrt(member.getCost()),
            alpha: (population.getGenerationCount() / member.getMutationCount()) - 0.7
          });
        }
        return _results;
      })();
      node = this.vis.selectAll("circle").data(this.layout.nodes({
        children: data
      }).filter(function(d) {
        return !d.children;
      })).style("fill", function(d) {
        return "#" + d.color;
      }).attr("r", function(d) {
        return d.r;
      }).attr("opacity", function(d) {
        return d.alpha;
      }).attr("transform", function(d) {
        return "translate(" + d.x + "," + d.y + ")";
      });
      node.enter().append("circle").style("fill", function(d) {
        return "#" + d.color;
      }).attr("r", function(d) {
        return d.r;
      }).attr("opacity", function(d) {
        return d.alpha;
      }).attr("transform", function(d) {
        return "translate(" + d.x + "," + d.y + ")";
      });
      return node.exit().remove();
    };

    return Simulator;

  })();

  global = typeof exports !== "undefined" && exports !== null ? exports : window;

  global.Chromosome = Chromosome;

  global.Population = Population;

  global.Simulator = Simulator;

}).call(this);
